### ISSUE TITLE
Project Website - Y/N?

### ISSUE THREAD

**Issue by mekline** [psych-ds/psych-DS#4]
We will likely outgrow a single README at some point; we should think about who the discrete audiences are and how to make sure people can find/use the standard. 

Maybe a readme for now and a website that's prepped for a launch at the same time & maybe a little more targeted at 'end users'?

(Starting this issue as a place to discuss what content the website should cover & a release timeline)

**Comment by KirstieJane** [comment]
I think seeing a GitHub repository makes people feel a little anxious so I'd advocate for a quite simple overview website that points to lots of the content on GitHub but can be the main landing page if someone googles the project :)

The other problem with relying on the README is that as there start to be more and more files in the repository that text gets pushed further and futher down the page. I like the idea of a website that puts the content front and centre.

Not a super strong opinion, but I do like the idea of having a `gh-pages` branch that hosts a nice website 😸

**Comment by jodeleeuw** [comment]
I second using `gh-pages` to host a simple website. It makes community-based edits possible without much overhead.

**Comment by mekline** [comment]
With gh-pages, will the url have the repository owner's (me, right now)
username in it? I don't necessarily want that; would like to think about
migrating to a gh organization(??) If that's the case.

**Comment by jodeleeuw** [comment]
By default, yes. The URL would be https://mekline.github.io/psych-DS. 

But you can use a domain name easily. Only cost is the registrar, so maybe $12/year or so.
